[package]
name = "fuzzy_clock_rust"
version = "0.1.0"
authors = ["Kevin Traver <kevintraver@gmail.com>"]

[dependencies]
chrono = "0.3"
serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"
lazy_static = "0.2.8"
rocket = "0.2.7"
rocket_codegen = "0.2.7"
